CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    customer_id BIGINT NOT NULL UNIQUE,

    CONSTRAINT fk_users_customer
        FOREIGN KEY (customer_id)
        REFERENCES customer(id)
);
